version: '3.7'

volumes:
    logs:
        driver: local

services:
    whisky:
        build:
          context: .
          dockerfile: Dockerfile
        working_dir: /var/www/site
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        restart: always
        hostname: whisky_svc
        container_name: whisky_svc
        environment:
            docker: "true"
        volumes:
            - .:/var/www/site:Z
        depends_on:
            - db
    db:
        image: mariadb:latest
        restart: always
        hostname: whisky-maria
        container_name: whisky-maria
        environment:
          MYSQL_DATABASE: 'db'
          # So you don't have to use root, but you can if you like
          MYSQL_USER: 'whisky'
          # You can use whatever password you like
          MYSQL_PASSWORD: 'whisky-maria@server2021'
          # Password for root access
          MYSQL_ROOT_PASSWORD: 'whisky-maria@server2021'
        ports:
          # <Port exposed> : < MySQL Port running inside container>
          - '3307:3306'
        expose:
          # Opens port 3306 on the container
          - '3307'
          # Where our data will be persisted
        volumes:
          - my-db:/var/lib/mysql
          - ./db.sql:/docker-entrypoint-initdb.d/dump.sql
      # Names our volume
volumes:
  my-db:


